vector_psu/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from programapp.views import (program_list,
                              program_detail,
                              program_list_json,
                              SpecialityListView,
                              program_create,
                              ProgramViewSet,
                              ProgramCreateView,
                              SpecialityViewSet
                              )
from courseapp.views import CourseListView,CourseDetailView,CourseViewSet
from helperapp.views import InterestViewSet

from rest_framework.routers import DefaultRouter

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView


router = DefaultRouter()
router.register(r'program', ProgramViewSet, basename='program')
router.register(r'course', CourseViewSet, basename='course')
router.register(r'speciality', SpecialityViewSet, basename='speciality')
router.register(r'interest', InterestViewSet, basename='interest')

urlpatterns = [
 #   path("",program_list),
    path("program/json/",program_list_json),
    path("program/create",ProgramCreateView.as_view()),
    #path("program/create",program_create),
    path("program/<int:pk>/",program_detail),
    path("course/",CourseListView.as_view()),
    path("course/<int:pk>/",CourseDetailView.as_view()),
    path("speciality/",SpecialityListView.as_view()),
    path('admin/', admin.site.urls),
    path('api/',include(router.urls)),
    re_path('.*',TemplateView.as_view(template_name='index.html'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programapp/models.py
from django.db import models

# Create your models here.


class Program(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название ОП")
    description = models.TextField(blank=True,verbose_name='Описание')
    date =models.DateField(blank=True,null=True)
    def ege_list(self):
        return self.programege_set.all()
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f"program/{self.id}/"

    def get_prof_cousr(self):
        return self.course_set.filter(prof_typ="P")

    def get_var_cousr(self):
        return self.course_set.filter(prof_typ="V")

    class Meta:
        verbose_name="Образовательаня программа"
        verbose_name_plural = "Образовательные программы"


class Ege(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class ProgramEge(models.Model):
    program = models.ForeignKey(Program,on_delete=models.CASCADE)
    ege = models.ForeignKey(Ege,on_delete=models.PROTECT)
    value = models.IntegerField()
    def ege_name(self):
        return self.ege.name


class Speciality(models.Model):
    name = models.CharField(max_length=255,verbose_name='Название')
    programapp = models.ForeignKey(Program,on_delete=models.PROTECT,verbose_name="ОП")
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name="Специальность"
        verbose_name_plural="Специальности"

programapp/forms.py
from django import forms
from django.forms import ModelForm
from programapp.models import Program

class SearchForm(forms.Form):
    program_name = forms.CharField(label="Название программы", max_length=100,required=False)
    date  = forms.DateField(label="Дата нача программы",required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class BootstrapModelForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
class ProgramForm(BootstrapModelForm):

    class Meta:
        model = Program
        fields= '__all__'

programapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.views.generic import ListView,CreateView

from programapp.models import Program,Speciality,ProgramEge

from django.contrib.auth.decorators import login_required
# Create your views here.
from programapp.forms import SearchForm,ProgramForm
from rest_framework import viewsets
from rest_framework import serializers

from django_filters import rest_framework as filters
from helperapp.models import Interest

class ProgramEgeSerializer(serializers.ModelSerializer):
    ege_name = serializers.CharField()
    class Meta:
        model = ProgramEge
        fields = "__all__"
class ProgramSerializer(serializers.ModelSerializer):
    ege_list = ProgramEgeSerializer(many=True,read_only=True)
    class Meta:
        model = Program
        fields = '__all__'

class ProgramFilter(filters.FilterSet):
    search = filters.CharFilter(field_name="name", lookup_expr='icontains')
    speciality =  filters.NumberFilter(method="get_speciality")

    def get_speciality(self,queryset,field_name,value):
        if value:
            queryset = queryset.filter(speciality__id=value)
        return queryset


    class Meta:
        model = Program
        fields = "__all__"

class ProgramViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and editing user instances.
    """
    serializer_class = ProgramSerializer
    queryset = Program.objects.all()
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ProgramFilter

class SpecialitySerializer(serializers.ModelSerializer):


    class Meta:
        model = Speciality
        fields = '__all__'

class SpecialityFilter(filters.FilterSet):
    search = filters.CharFilter(field_name="name", lookup_expr='icontains')
    interest = filters.ModelMultipleChoiceFilter(
        field_name='interest',
        lookup_expr='in',
        queryset= Interest.objects.all(),
        method="get_interest"
    )
    def get_speciality(self,queryset,field_name,value):
        print("spec",value)
        if value:
            queryset = queryset.filter(speciality__id=value)
        return queryset



    def get_interest(self,queryset,field_name,value):
        if value:
            queryset = queryset.filter(interest__in=value)
        return queryset.order_by().distinct()



    class Meta:
        model = Speciality
        fields = "__all__"

class SpecialityViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and editing user instances.
    """
    serializer_class = SpecialitySerializer
    queryset = Speciality.objects.all()
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = SpecialityFilter




@login_required
def program_list(request):

    form = SearchForm(request.GET)
    program_list =Program.objects.all()

    if form.is_valid():
        name = form.cleaned_data.get('program_name')
        date= form.cleaned_data.get('date')
        if name:
            program_list=program_list.filter(name__icontains=name)
        if date:
            program_list =program_list.filter(date__gt=date)
    else:
        pass
    context = {
        "program_list":program_list,
        'form':form,
    }
    return render(request,'programapp/program_list.html',context)
@login_required
def program_list_json(request):

    form = SearchForm(request.GET)
    program_list =Program.objects.all()

    if form.is_valid():
        name = form.cleaned_data.get('program_name')
        date= form.cleaned_data.get('date')
        if name:
            program_list=program_list.filter(name__icontains=name)
        if date:
            program_list =program_list.filter(date__gt=date)
    else:
        pass
    data = []
    for x in program_list:
        course_list = []
        for course in x.course_set.all():
            course_list.append({'name':course.name})
        tmp = {'name':x.name,'id':x.id,'course_set':course_list}
        data.append( tmp)
    return JsonResponse({'data':data})



def program_create(request):
    if request.method =='GET':
        form = ProgramForm()
    else:
        form = ProgramForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'form':form,
    }
    return render(request,'programapp/program_form.html',context)

class ProgramCreateView(CreateView):
    model = Program
    form_class = ProgramForm
    #fields="__all__"

def program_detail(request,pk):
    obj = Program.objects.get(id=pk)
    base_cousr = obj.course_set.filter(prof_typ="B")

    known_area =[
        {"name":'Физика',
         "code":"FZ",
         'course':base_cousr.filter(known_area="FZ")
         },
        {"name":'математика',
         "code":"MT",
         'course':base_cousr.filter(known_area="MT")
         },
        {"name":'ИТ',
         "code":"IT",
         'course':base_cousr.filter(known_area="IT")
         },
    ]
    context = {
        "program":obj,
        "known_area":known_area,
    }
    return render(request,'programapp/program_detail.html',context)

class SpecialityListView(ListView):
    model = Speciality

programapp/templates/programapp/program_detail.html
{% extends 'base.html'%}
{% block content%}
<div class="row">
    <div class="col-8">
<h1> ОП {{program.name}}</h1>
<h1> ОП {% if program.name == "tet"%}</h1>
{%endif%}
<div >{{program.description}}</div>
</div>
    <div class="col-4">
            <h2> Специальности</h2>
            {% for speciality in program.speciality_set.all%}
                <div> {{speciality}} </div>
            {%endfor%}
            </div>
            </div>

<h2> Базовый блок дисциплин</h2>
<div class=" row row-cols-1 row-cols-md-3">
    {% for area in known_area%}
        <div class="col">
    <div class="area-{{area.code}}">
        <h5 class="card-title"> {{area.name}}</h5>
        <div class="card h-100 ">
        <div class="card-body">
            <ul>
        {% for cours in area.course %}
        <li> <a href="{{cours.get_absolute_url}}">{{cours}}</a> </li>
        {%endfor%}
            </ul>
    </div>
    </div>
    </div>
    </div>
    {%endfor%}
    </div>
    <div class="row  ">
        <div class="col-sm-12 col-md-4">
            <h2> Профессиональный блок</h2>
            <ul>
            {% for course in program.get_prof_cousr%}
                <li class="area-{{course.known_area}} course-name"> {{course}} </li>
            {%endfor%}
            <ul>
        </div>

        <div class="col-sm-12 col-md-4">
            <h2> По выбору блок</h2>
            {% for course in program.get_var_cousr%}
            <div class="area-{{course.known_area}} course-name"> {{course}} </div>
            {%endfor%}
        </div>

    </div>

<style>
.area-FZ.course-name{
     color:blue
}
.area-MT.course-name{
     color:red
}

 .area-FZ .card-title{
     color:blue
 }
 .area-FZ .card-body{
     background-color:#0000ff0d
 }



 .area-MT .card-title{
     color:red
 }
 .area-MT .card-body{
     background-color:#ff000012
 }



 .area-IT .card-title{
     color:green
 }
 .area-IT .card-body{
     background-color:#00ff4c12
 }
 .card{
    border-radius:40px
}

</style>
</style>
{%endblock%}

programapp/templates/programapp/program_form.html
{% extends 'base.html'%}
{% block content%}
<h1> Созадть ОБразовательную программу</h1>
<div class="row">
    <div class="col-8">
        <form method="POST">
        {{form}}
        {% csrf_token%}
        <button> сохранить </button>
        </form>
    </div >
</div>
{%endblock%}

programapp/templates/programapp/program_list.html
{% extends 'base.html'%}
{% block content%}
<h1>Список</h1>

<form>
    {{form}}
</form>
<div id="data"></div>
<script>

function renderProgram(program){
    let cours_list = '<ul>'
    if (program.course_set){
    for (let cours of program.course_set){
        cours_list+= '<li>' +cours.name +'</li>'
    }
    }
    cours_list+='</ul>'
    return `<div><h2> ${program.name} </h2> ${cours_list}</div>`

}
async function getProgramList(){
    let input_program_name = document.getElementById('id_program_name')
    let program_name = input_program_name.value
    let response = await fetch("api/program/?program_name="+program_name)
    let data =await response.json()
    let el = document.getElementById('data')
    let str = '<ul>'
    for (program  of data){
        str+= renderProgram(program)
    }
    str+='</ul>'
    el.innerHTML=str

    console.log(data)
}

let input_program_name = document.getElementById('id_program_name')
input_program_name.addEventListener('input',getProgramList)
getProgramList()


</script>

{%endblock%}

programapp/templates/programapp/speciality_list.html
{% extends 'base.html'%}
{% block content%}
<h1>Список Специальностей</h1>
{% for program in speciality_list%}

<h2> <a href="{{program.get_absolute_url}}"> {{program}} </a> </h2>
    {% for cours in program.course_set.all%}
    <div> {{cours}} </div>
    {%endfor%}
{%endfor%}
{%endblock%}